function FavoriteVideoGamesProcess()
{
  // Create HTML code
  var string;
  string = "<ul>"
			+ "<li>Killer Instinct (2013) (Microsoft XBox One)</li>"
			+ "<li>Call Of Duty: Black Ops III (Microsoft XBox One and Sony PlayStation 4 (PS4))</li>"
			+ "<li>Super Mario Maker (Nintendo Wii U and Nintendo 3DS)</li>"
			+ "<li>Spider-Man: Shattered Dimensions (Microsoft XBox 360)</li>"
			+ "<li>Injustice Gods Among Us (Microsoft XBox 360 and Sony PlayStation 4 (PS4))</li>"
			+ "<li>Teenage Mutant Ninja Turtles: Mutants In Manhattan (Microsoft XBox One)</li>"
			+ "<li>Call of Duty: Ghosts (Microsoft XBox One, Microsoft XBox 360 and Sony PlayStation 4 (PS4))</li>"
			+ "<li>Call of Duty: Advanced Warfare (Microsoft XBox One and Sony PlayStation 4 (PS4))</li>"
			+ "<li>Call of Duty 4: Modern Warfare (Microsoft XBox 360)</li>"
			+ "<li>Bayonetta 2 (Nintendo Wii U)</li>"
			+ "<li>Guitar Hero Live (Microsoft XBox One)</li>"
			+ "<li>Street Fighter V (Sony PlayStation 4 (PS4))</li>"
			+ "<li>Call of Duty: Infinite Warfare (Microsoft XBox One and Sony PlayStation 4 (PS4))</li>"
			+ "<li>Watch Dogs (Microsoft XBox One)</li>"
			+ "<li>Watch Dogs 2 (Sony PlayStation 4 (PS4))</li>"
			+ "<li>Assassin's Creed (game) (Microsoft XBox 360)</li>"
			+ "<li>Puyo Puyo Tetris (Nintendo Switch and Sony PlayStation 4 (PS4))</li>"
			+ "<li>Injustice 2 (Microsoft XBox One and and Sony PlayStation 4 (PS4))</li>"
			+ "<li>Hey, Pikmin! (Nintendo 3DS)</li>"
			+ "<li>Bulletstorm (Microsoft XBox 360 and Microsoft XBox One)</li>"
			+ "<li>Ultimate Marvel VS. Capcom 3 (Microsoft XBox 360, Microsoft XBox One, and Sony PlayStation 4 (PS4))</li>"
			+ "<li>Spider-Man: Edge of Time (Microsoft XBox One, Nintendo DS, and Nintendo 3DS)</li>"
			+ "<li>Ultra Street Fighter II: The Final Challengers (Nintendo Switch)</li>"
			+ "<li>Batman: Arkham Knight (Microsoft XBox One and Sony PlayStation 4 (PS4))</li>"
			+ "<li>Marvel VS Capcom: Infinite (Microsoft XBox One)</li>"
			+ "<li>Sonic Mania (Microsoft XBox One)</li>"
			+ "<li>Splatoon 2 (Nintendo Switch)</li>"
			+ "<li>ARMS (Nintendo Switch)</li>"
			+ "<li>Prototype (Microsoft XBox 360, Microsoft XBox One and Sony PlayStation 4 (PS4))</li>"
			+ "<li>Prototype 2 (Microsoft XBox 360, Microsoft XBox One and Sony PlayStation 4 (PS4))</li>"
			+ "<li>Star Fox Zero (Nintendo Wii U)</li>"
			+ "<li>Splatoon (Nintendo Wii U)</li>"
			+ "<li>Gears of War 4 (Microsoft XBox One)</li>"
			+ "<li>Crash Bandicoot: N. Sane Trilogy (Sony PlayStation 4 (PS4))</li>"
			+ "<li>Puzzles and Dragons Z / Puzzles and Dragons: Super Mario Bros Edition (Nintendo 3DS)</li>"
			+ "<li>Kid Icarus: Uprising (Nintendo 3DS)</li>"
			+ "<li>Super Smash Bros. for Nintendo 3DS (Nintendo 3DS)</li>"
			+ "<li>Hyrule Warriors Legends (Nintendo 3DS)</li>"
			+ "<li>Mario Kart 8 Deluxe (Nintendo Switch)</li>"
			+ "<li>The Legend of Zelda: Breath of the Wild (Nintendo Switch)</li>"
			+ "<li>Lego City Undercover (Nintendo Switch)</li>"
			+ "<li>Metroid Prime: Federation Force (Nintendo 3DS)</li>"
			+ "<li>Metroid Prime (Nintendo GameCube and Nintendo Wii)</li>"
			+ "<li>Metroid Prime 2: Echoes (Nintendo GameCube and Nintendo Wii)</li>"
			+ "<li>Metroid Prime 3 Corruption (Nintendo Wii)</li>"
			+ "<li>Metroid: Other M (Nintendo Wii)</li>"
			+ "<li>Assassin's Creed II (Microsoft XBox 360 and Sony PlayStation 4 (PS4))</li>"
			+ "<li>Assassin's Creed Brotherhood (Microsoft XBox 360 and Sony PlayStation 4 (PS4))</li>"
			+ "<li>Batman: Arkham Asylum (Microsoft XBox 360 and Microsoft XBox One)</li>"
			+ "<li>Batman: Arkham City (Microsoft XBox 360 and Microsoft XBox One)</li>"
			+ "<li>Sonic: Lost World (Nintendo 3DS and Nintendo Wii U)</li>"
			+ "<li>Super Smash Bros. For Wii U (Nintendo Wii U)</li>"
			+ "<li>Super Smash Bros. (Nintendo 64)</li>"
			+ "<li>Sonic Generations (Microsoft XBox 360 and Nintendo 3DS)</li>"
		+ "</ul>";
    // obtain a reference to the <div>
    myDiv = document.getElementById("myDivFavoriteVideoGamesElement");
    // add content to the <div> element
    myDiv.innerHTML = string;
}
