function ComputerProgrammingSkillsProcess()
{
	// Create HTML code
	var string;
	string = "<table border = " + "3" + ">"
			+ "<caption>Computer Programming Skills</caption>"
			+ "<tr>"
				+ "<th>Name</th>"
				+ "<th>First Appeared</th>"
				+ "<th>Paradigm</th>"
				+ "<th>Typing Discipline</th>"
				+ "<th>Designed By</th>"
				+ "<th>Implementation Language(s)</th>"
				+ "<th>Resource Number(s)</th>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>C++</td>"
				+ "<td>1983</td>"
				+ "<td>Multi-Paradigm, Procedural, Functional, Object-Oriented, Generic</td>"
				+ "<td>Static, Nominative, Partially Inferred</td>"
				+ "<td>Bjarne Stroustrup</td>"
				+ "<td>C++ or C</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">1</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>C#</td>"
				+ "<td>2000</td>"
				+ "<td>Structured, Imperative, Object-Oriented, Event-Driven, Task-Driven, Functional, Generic, Reflective, Concurrent</td>"
				+ "<td>Static, Dynamic, Strong, Safe, Nominative, Partially Inferred</td>"
				+ "<td>Microsoft</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">2</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Java</td>"
				+ "<td>1995</td>"
				+ "<td>Multi-Paradigm, Object-Oriented (Class-Based), Structured, Imperative, Generic, Reflective, Concurrent</td>"
				+ "<td>Static, Strong, Safe, Nominative, Manifest</td>"
				+ "<td>James Gosling</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">3</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>JavaScript</td>"
				+ "<td>1995</td>"
				+ "<td>Multi-Paradigm, Object-Oriented (Prototype-Based), Imperative, Functional, Event-Driven</td>"
				+ "<td>Dynamic, Duck</td>"
				+ "<td>Brendan Eich</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">4</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>HTML (HyperText Markup Language)</td>"
				+ "<td>1993</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>Tim Berners-Lee</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">5</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>CSS (Cascading Style Sheet)</td>"
				+ "<td>1996</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>Hakon Wium Lee</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">6</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>AJAX (Asynchronous JavaScript and XML)</td>"
				+ "<td>1996</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">7</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>MySQL (Structured Query Language)</td>"
				+ "<td>1995</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>David Axmark, Allan Larsson and Micheal " + "Monty" + "Widenius</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">8</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>PHP (Personal Home Page)</td>"
				+ "<td>1995</td>"
				+ "<td>Dynamic, Weak, Gradual</td>"
				+ "<td>Imperative, Object-Oriented, Procedural, Reflective</td>"
				+ "<td>Rasmus Lerdorf</td>"
				+ "<td>C, C++</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">9</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>F#</td>"
				+ "<td>2005</td>"
				+ "<td>Static, Strong, Inferred</td>"
				+ "<td>Multi-Paradigm, Functional, Imperative, Object-Oriented, Metaprogramming, Reflective, Concurrent</td>"
				+ "<td>Don Syme, Microsoft Research</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">10</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>XML (eXtensible Markup Language)</td>"
				+ "<td>1996</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">11</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Visual BASIC (Beginner's All-Purpose Symbolic Instruction Code)</td>"
				+ "<td>1991</td>"
				+ "<td>Static, Strong</td>"
				+ "<td>Object-Based, Event-Driven</td>"
				+ "<td>Alan Cooper</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">12</a>, <a href=" + "Website About Me - Works Cited.html" + ">13</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>VBScript (Microsoft Visual Basic Scripting Edition)</td>"
				+ "<td>1996</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>Alan Cooper</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">14</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Trello</td>"
				+ "<td>2011</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>Joel Spolsky</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">14</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>WordPress</td>"
				+ "<td>2003</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>Matt Mullenwug, Mike Little</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">16</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Typeform</td>"
				+ "<td>2012</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>Robert Mu&ntilde;oz, David Okuniev</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">17</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Google Analytics</td>"
				+ "<td>2005</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>Google</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">18</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Google Tag Manager</td>"
				+ "<td>2012</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>Google</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">19</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Gliffy</td>"
				+ "<td>2005</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>Chris Kohlhardt, Clint Dickson</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">20</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Google Sheets</td>"
				+ "<td>2006</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>Google</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">21</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Google Docs</td>"
				+ "<td>2006</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>Google</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">21</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Google Slides</td>"
				+ "<td>2006</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>Google</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">21</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Google Page Speed</td>"
				+ "<td>2010</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>Google</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">22</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>C</td>"
				+ "<td>1972</td>"
				+ "<td>Imperative (Procedural), Structured</td>"
				+ "<td>Static, Weak, Manifest, Nominal</td>"
				+ "<td>Dennis Ritchie</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">23</a></td>"
			+ "</tr>"
		+ "</table>"
		+ "<ul>"
			+ "<li>Android Development</li>"
			+ "<li>Web Development</li>"
			+ "<li>Hot Jar</li>"
			+ "<li>LearnDash</li>"
			+ "<li>Tag Cloud</li>"
			+ "<li>Webpage Test</li>"
			+ "<li>Wikia</li>"
			+ "<li>Google Chrome Developer Tools</li>"
			+ "<li>Conversion Fly</li>"
			+ "<li>Github</li>"
		+ "</ul>";
	// obtain a reference to the <div>
	myDiv = document.getElementById("myDivComputerProgrammingSkillsElement");
	// add content to the <div> elementFromPoint
	myDiv.innerHTML = string;
}
