function FavoriteStoresProcess
{
	// Create HTML code
	var string;
	string = "<table border = " + "3" + ">"
			+ "<caption>Favorite Stores</caption>"
			+ "<tr>"
				+ "<th>Name</th>"
				+ "<th>Type</th>"
				+ "<th>Industry(ies)</th>"
				+ "<th>Founded</th>"
				+ "<th>Headquarters</th>"
				+ "<th>Number of Locations</th>"
				+ "<th>Product(s)</th>"
				+ "<th>Division(s)</th>"
				+ "<th>Number of Employees</th>"
				+ "<th>Founder(s)</th>"
				+ "<th>Revenue</th>"
				+ "<th>Operating Income</th>"
				+ "<th>Net Income</th>"
				+ "<th>Total Assets</th>"
				+ "<th>Total Equity</th>"
				+ "<th>Area Served</th>"
				+ "<th>Resource Number</th>"
			+ "</tr>"
			+ "<tr>"
				+ "<td><a href=" + "http://www.gamestop.com/" + ">GameStop</a></td>"
				+ "<td>Public</td>"
				+ "<td>Retail</td>"
				+ "<td>1984</td>"
				+ "<td>Grapevine, Texas</td>"
				+ "<td>7,276</td>"
				+ "<td>Video Games, Consoles, Accessories</td>"
				+ "<td>Video Game Brands, Technology Brands</td>"
				+ "<td>20,000</td>"
				+ "<td>James McCurry, Gary M. Kusin</td>"
				+ "<td>$9.225 Billion (US)</td>"
				+ "<td>$135.6 Million (US)</td>"
				+ "<td>$34.7 Million (US)</td>"
				+ "<td>$5.042 Billion (US)</td>"
				+ "<td>$2.215 Billion (US)</td>"
				+ "<td>Australia, Austria, Canada, Denmark, Finland, France, Germany, Italy, Ireland, Netherlands, New Zealand, Norway, Sweden, Switzerland, United States</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">1</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td><a href=" + "https://www.walmart.com/" + ">Walmart</a></td>"
				+ "<td>Public</td>"
				+ "<td>Retail</td>"
				+ "<td>1962</td>"
				+ "<td>Bentonville, Arkansas</td>"
				+ "<td>11,718</td>"
				+ "<td>Electronics, Movies and Music, Home and Furniture, Home Improvement, Clothing, Footwear, Jewelry, Toys, Health and Beauty, Pet Supplies, Sporting Goods and Fitness, Auto, Photo Finishing, Craft Supplies, Party Supplies, Grocery</td>"
				+ "<td>Walmart U.S. Walmart International, Sam's Club, Global eCommerce</td>"
				+ "<td>2.3 Million</td>"
				+ "<td>Sam Walton</td>"
				+ "<td>$500.34 Billion (US)</td>"
				+ "<td>$20.437 Billion (US)</td>"
				+ "<td>$9.862 Billion (US)</td>"
				+ "<td>$204.52 Billion (US)</td>"
				+ "<td>$77.869 Billion (US)</td>"
				+ "<td>Worldwide</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">2</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td><a href=" + "https://www.target.com/" + ">Target</a></td>"
				+ "<td>Public</td>"
				+ "<td>Retail</td>"
				+ "<td>1902</td>"
				+ "<td>Minneapolis, Minnesota</td>"
				+ "<td>1,828</td>"
				+ "<td>Beauty and Health Products, Bedding, Clothing and Accessories, Electronics, Food, Furniture, Housewares, Jewelry, Gardening Supplies, Pet Supplies, Shoes, Sporting Goods, Toys/Games, Small Appliances, Office Supplies, Books, Movies, Music</td>"
				+ "<td>Financial and Retail Services, Target Sourcing Services</td>"
				+ "<td>341,000</td>"
				+ "<td>George Dayton</td>"
				+ "<td>$71.879 Billion (US)</td>"
				+ "<td>$4.312 Billion (US)</td>"
				+ "<td>$2.934 Billion (US)</td>"
				+ "<td>$38.999 Billion (US)</td>"
				+ "<td>$11.709 Billion (US)</td>"
				+ "<td>United States</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">3</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td><a href=" + "http://www.bestbuy.com/" + ">Best Buy</a></td>"
				+ "<td>Public</td>"
				+ "<td>Retail</td>"
				+ "<td>1966</td>"
				+ "<td>Richfield, Minnesota</td>"
				+ "<td>1,026</td>"
				+ "<td>Consumer Electronics</td>"
				+ "<td>Geek Squad, Magnolia, Pacific Sales</td>"
				+ "<td>125,000</td>"
				+ "<td>Richard M. Schulze</td>"
				+ "<td>$42.151 Billion (US)</td>"
				+ "<td>$1.843 Billion (US)</td>"
				+ "<td>$1.000 Billion (US)</td>"
				+ "<td>$13.049 Billion (US)</td>"
				+ "<td>$3.612 Billion (US)</td>"
				+ "<td>United States & Canada</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">4</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td><a href=" + "https://www.kohls.com/" + ">Kohl's</a></td>"
				+ "<td>Public</td>"
				+ "<td>Retail</td>"
				+ "<td>1962</td>"
				+ "<td>Menomonee Falls, Wisconsin</td>"
				+ "<td>1,155</td>"
				+ "<td>Clothing, Footwear, Bedding, Furniture, Jewelry, Beauty Products, Electronics, Housewares</td>"
				+ "<td>None</td>"
				+ "<td>138,000</td>"
				+ "<td>Maxwell Kohl</td>"
				+ "<td>$18.686 Billion (US)</td>"
				+ "<td>$1.183 Billion (US)</td>"
				+ "<td>$556 Million (US)</td>"
				+ "<td>$13.574 Billion (US)</td>"
				+ "<td>$5.177 Billion (US)</td>"
				+ "<td>United States</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">5</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td><a href=" + "http://www.shopko.com/" + ">Shopko</a></td>"
				+ "<td>Private</td>"
				+ "<td>Retail</td>"
				+ "<td>1962</td>"
				+ "<td>Green Bay, Wisconsin</td>"
				+ "<td>357</td>"
				+ "<td>Clothing, Footwear, Bedding, Furniture, Jewelry, Beauty Products, Electronics, Market, Housewares, Contact Lenses</td>"
				+ "<td>None</td>"
				+ "<td>16,900</td>"
				+ "<td>James Ruben</td>"
				+ "<td>$3.25 Billion (US)</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>California, Idaho, Illinois, Iowa, Kansas, Michigan, Minnesota, Montana, Nebraska, Nevada, Oregon, South Dakota, Utah, Washington and Wisconsin (Shopko), Wisconsin (Shopko Express), Arizona, Colorado, Iowa, Idaho, Illinois, Indiana, Kansas, Kentucky, Michigan, Minnesota, Missouri, Montana, Nebraska, New Mexico, North Dakota, Ohio, Oklahoma, South Dakota, Tennessee, Texas, Utah, Washington, Wisconsin and Wyoming (Shopko Hometown)</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">6</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td><a href=" + "https://www.cub.com/" + ">Cub Foods</a></td>"
				+ "<td>Subsidiary</td>"
				+ "<td>Retail, Grocery</td>"
				+ "<td>1968</td>"
				+ "<td>Stillwater, Minnesota</td>"
				+ "<td>81</td>"
				+ "<td>Bakery, Dairy, Deli, Frozen Foods, Grocery, Meat, Pharmacy, Produce, Seafood, Snacks, Liquor</td>"
				+ "<td>None</td>"
				+ "<td>100+</td>"
				+ "<td>Charles Hooley, Jack Hooley, Robert Thueson, Culver Davis Jr.</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>United States</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">7</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td><a href=" + "http://www.dollargeneral.com/" + ">Dollar General</a></td>"
				+ "<td>Public</td>"
				+ "<td>Discount Retailer</td>"
				+ "<td>1939 (J.L. Turner and Son), 1968 (Dollar General Corporation)</td>"
				+ "<td>Goodlettsville, Tennessee</td>"
				+ "<td>14,000</td>"
				+ "<td>Clothing, Cleaning Supplies, Home Decor, Health & Beauty, Aids, Pet Supplies, Toys, Seasonal Items, Grocery</td>"
				+ "<td>Dollar General Market</td>"
				+ "<td>100+</td>"
				+ "<td>J.L. Turner, Cal Turner</td>"
				+ "<td>$20.369 Billion (US)</td>"
				+ "<td>$1.940 Billion (US)</td>"
				+ "<td>$1.165 Billion (US)</td>"
				+ "<td>$11.258 Billion (US)</td>"
				+ "<td>None</td>"
				+ "<td>Contiguous United States except for the Northwest</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">8</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td><a href=" + "https://www.officedepot.com/" + ">OfficeMax</a></td>"
				+ "<td>Subsidiary, Brand</td>"
				+ "<td>Retail</td>"
				+ "<td>1988</td>"
				+ "<td>Boca Raton, Florida</td>"
				+ "<td>941</td>"
				+ "<td>Office Supplies</td>"
				+ "<td>None</td>"
				+ "<td>100+</td>"
				+ "<td>Bob Hurwitz, Michael Feuer</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>United States, Canada and Mexico</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">9</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td><a href=" + "https://www.barnesandnoble.com/" + ">Barnes & Noble</a></td>"
				+ "<td>Public</td>"
				+ "<td>Retail</td>"
				+ "<td>1886</td>"
				+ "<td>New York City, New York</td>"
				+ "<td>781</td>"
				+ "<td>Nook, SparkNotes</td>"
				+ "<td>None</td>"
				+ "<td>26,000</td>"
				+ "<td>Charles M. Barnes, William Barnes, G. Clifford Noble, Leonard Riggio</td>"
				+ "<td>$4.164 Billion (US)</td>"
				+ "<td>$14.656 Million (US)</td>"
				+ "<td>$24.446 Million (US)</td>"
				+ "<td>$2.013 Billion (US)</td>"
				+ "<td>$604.510 Million (US)</td>"
				+ "<td>United States</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">10</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td><a href=" + "https://www.hpb.com/home" + ">Half Price Books</a></td>"
				+ "<td>Public</td>"
				+ "<td>Retail (Speciality)</td>"
				+ "<td>1972</td>"
				+ "<td>Dallas, Texas</td>"
				+ "<td>127</td>"
				+ "<td>Books, Records, CDs, DVDs, Magazines, Video Games</td>"
				+ "<td>None</td>"
				+ "<td>100+</td>"
				+ "<td>Ken Gjemre, Pat Anderson</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>United States</td>"
				+ "<td><a href=" + "Website About Me - Works Cited.html" + ">11</a></td>"
			+ "</tr>"
		+ "</table>";
	// obtain a reference to the <div>
	myDiv = document.getElementById("myDivFavoriteStoresElement");
	// add content to the <div> elementFromPoint
	myDiv.innerHTML = string;
}
