function FavoriteGamingConsolesProcess()
{
	// Create HTML code
	var string;
	string = "<table border = " + "3" + ">"
			+ "<caption>Favorite Gaming Consoles</caption>"
			+ "<tr>"
				+ "<th>Name</th>"
				+ "<th>Developer(s)</th>"
				+ "<th>Manufacturer(s)</th>"
				+ "<th>Type</th>"
				+ "<th>Date(s) of Release (depending on the type and region)</th>"
				+ "<th>Date of Discontinuation</th>"
				+ "<th>Best Selling Game(s)</th>"
				+ "<th>Units Sold</th>"
				+ "<th>Introductory Price(s)</th>"
				+ "<th>Predecessor</th>"
				+ "<th>Successor</th>"
				+ "<th>Generation</th>"
				+ "<th>Controller Input(s)</th>"
				+ "<th>Media</th>"
				+ "<th>Storage</th>"
				+ "<th>Operating System</th>"
				+ "<th>CPU (Central Processing Unit)(s)</th>"
				+ "<th>Graphics</th>"
				+ "<th>Resource Number</th>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Nintendo Switch</td>"
				+ "<td>Nintendo</td>"
				+ "<td>Nintendo Platform Technology Development (PTD), Foxconn, Hosiden</td>"
				+ "<td>Hybrid Video Game Console</td>"
				+ "<td>March 3, 2017 (Worldwide)</td>"
				+ "<td>TBD</td>"
				+ "<td>Super Mario Odyssey (9.07 Million)</td>"
				+ "<td>17.79 Million</td>"
				+ "<td>$299.99</td>"
				+ "<td>Wii U</td>"
				+ "<td>TBD</td>"
				+ "<td>Eighth</td>"
				+ "<td>Joy-Con, Pro Controller</td>"
				+ "<td>Game Card, Digital Distribution (Nintendo eShop)</td>"
				+ "<td>32 GB Internal Flash Memory</td>"
				+ "<td>Nintendo Switch System Software</td>"
				+ "<td>Octa-Core (4xARM Cortex-A57 & 4xARM Cortex-A53) @ 1.020 GHz</td>"
				+ "<td>Nvidia GM20B Maxwell-based GPU @ 307.2 - 384 MHz while undocked, 307.2 - 768 MHz while docked</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">1</a>, <a href=" + "Website About Me - Works Cited - mobile.html" + ">2</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Wii U</td>"
				+ "<td>Nintendo Integrated Research and Development (IRD), Nintendo Technology Development (Ntd)</td>"
				+ "<td>Nintendo, Foxconn, Mitsumi</td>"
				+ "<td>Home Video Game Console</td>"
				+ "<td>November 18, 2012 (United States and Canada), November 29, 2012 (Mexico and South Africa), November 30, 2012 (Europe and Australasia), December 8, 2012 (Japan), November 26, 2013 (Brazil)</td>"
				+ "<td>January 31, 2017</td>"
				+ "<td>Mario Kart 8 (8.26 Million)</td>"
				+ "<td>13.56 Million</td>"
				+ "<td>$299 (Basic), $349 (Deluxe and Premium)</td>"
				+ "<td>Wii</td>"
				+ "<td>Nintendo Switch</td>"
				+ "<td>Eighth</td>"
				+ "<td>Wii U GamePad, Wii U Pro Controller, Wii Remote (Plus)</td>"
				+ "<td>Wii U Optical Disc, Wii Optical Disc, Digital Distribution (Nintendo eShop)</td>"
				+ "<td>8 or 32 GB Internal Flash Memory, SD/SDHC Card, USB Storage Device</td>"
				+ "<td>Wii U System Software</td>"
				+ "<td>1.24 GHz Tri-Core IBM PowerPC " + "Espresso" + "</td>"
				+ "<td>550 MHz AMD Radeon " + "Latte" + "</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">3</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Nintendo 3DS</td>"
				+ "<td>Nintendo RED (Research & Engineering Department)</td>"
				+ "<td>Nintendo, Foxconn</td>"
				+ "<td>Handheld Game Console</td>"
				+ "<td>February 26, 2011 (Japan), March 27, 2011 (Europe), March 27, 2011 (North America), March 31, 2011 (Australasia, 3DS), July 28 2012 (Japan and Europe), August 19, 2012 (North America), August 23, 2012 (Australasia, 3DS XL)</td>"
				+ "<td>TBD</td>"
				+ "<td>Mario Kart 7 (16.76 Million)</td>"
				+ "<td>71.99 Million</td>"
				+ "<td>$249 (3DS), $199 (3DS XL)</td>"
				+ "<td>Nintendo DS</td>"
				+ "<td>TBD</td>"
				+ "<td>Eighth</td>"
				+ "<td>None</td>"
				+ "<td>Nintendo 3DS Game Card, Nintendo DS Game Card, Digital Distribution (Nintendo eShop), SD/SDHC Card</td>"
				+ "<td>1 GB Internal Flash Memory, 2 GB SD Card (3DS), 4 GB SDHC Card (3DS XL), Cartridge Save</td>"
				+ "<td>Nintendo 3DS System Software</td>"
				+ "<td>268MHz Dual-Core ARM11 MPCore, Single-Core ARM9</td>"
				+ "<td>DMP PICA200 GPU</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">4</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Nintendo DS</td>"
				+ "<td>Nintendo</td>"
				+ "<td>Foxconn</td>"
				+ "<td>Handheld Game Console</td>"
				+ "<td>November 21, 2004 (North America), December 2, 2004 (Japan), February 24, 2005 (Australasia), March 11, 2005 (Europe, DS), March 2, 2006 (Japan), June 1, 2006 (Australasia), June 11, 2006 (North America), June 23, 2006 (Europe), January 18, 2007 (South Korea, DS Lite), November 1, 2008 (Japan), April 2, 2009 (Australasia), April 3, 2009 (Europe), April 5, 2009 (North America, DSi), November 21, 2009 (Japan), March 5, 2010 (Europe), March 28, 2010 (North America), April 15, 2010 (Australasia, DSi XL)</td>"
				+ "<td>TBD</td>"
				+ "<td>New Super Mario Bros. (30.80 Million)</td>"
				+ "<td>154.02 Million (DS), 93.86 Million (DS Lite), 41 Million (DSi)</td>"
				+ "<td>$149.99 (DS), $129.99 (DS Lite), $149 (DSi)</td>"
				+ "<td>Game Boy Advance (GBA)</td>"
				+ "<td>Nintendo 3DS</td>"
				+ "<td>Seventh</td>"
				+ "<td>None</td>"
				+ "<td>Nintendo Game Card, ROM cartridge</td>"
				+ "<td>Cartridge save 256 KB flash memory</td>"
				+ "<td>None</td>"
				+ "<td>Two ARM Architecture Processors</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">5</a>, <a href=" + "Website About Me - Works Cited - mobile.html" + ">6</a>, <a href=" + "Website About Me - Works Cited - mobile.html" + ">7</a>, <a href=" + "Website About Me - Works Cited - mobile.html" + ">8</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Xbox One</td>"
				+ "<td>Microsoft</td>"
				+ "<td>Flextronics, Foxconn</td>"
				+ "<td>Home Video Game Console</td>"
				+ "<td>November 22, 2013 (North America, Europe (some countries, September 2, 2014 for other countries), Australasia and Brazil), September 4, 2014 (Japan), September 29, 2014 (China)</td>"
				+ "<td>TBD</td>"
				+ "<td>Halo 5: Guardians (5 Million)</td>"
				+ "<td>19 Million</td>"
				+ "<td>$499</td>"
				+ "<td>Xbox 360</td>"
				+ "<td>TBD</td>"
				+ "<td>Eighth</td>"
				+ "<td>Xbox One Controller, Kinect for Xbox One, Xbox App, Xbox One Media Remote</td>"
				+ "<td>UHD Blu-Ray (S and X Models), Blu-Ray, DVD, CD (All Models)</td>"
				+ "<td>500 GB, 1 or 2 TB Internal Hard Drive, USB 3.0 Storage Device 256 GB or Greater</td>"
				+ "<td>Xbox One System Software</td>"
				+ "<td>Custom 1.75 GHz AMD 8-Core APU (2 Quad-Core Jaguar Modules) (Orginal and S Model), Custom 2.3 GHz AMD 8-Core APU (2 Quad-Core Evolved Jaguar Modules) (X Model)</td>"
				+ "<td>Xbox One: 853 MHz, Xbox One S: 914 MHz, Xbox One X: 1.172 GHz AMD Radeon GCN Architecture (Built Into APU)</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">9</a>, <a href=" + "Website About Me - Works Cited - mobile.html" + ">10</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Xbox 360</td>"
				+ "<td>Microsoft</td>"
				+ "<td>Flextronics, Wistron, Celestica, Foxconn</td>"
				+ "<td>Home Video Game Console</td>"
				+ "<td>November 22, 2005 (North America), December 2, 2005 (Europe), December 10, 2005 (Japan), February 2, 2006 (Colombia and Mexico), February 24, 2006 (South Korea), March 16, 2006 (Hong Kong, Singapore and Taiwan), March 23, 2006 (Australasia), July 7, 2006 (Chile), September 25, 2006 (India), September 29, 2006 (South Africa), November 3, 2006 (Czech Republic and Poland), December 1, 2006 (Brazil), February 11, 2008 (Russia), February 25, 2008 (Peru), October 28, 2008 (United Arab Emirates), January 1, 2009 (Nigera and Turkey), March 1, 2010 (Seychelles, Original), June 28, 2010 (North America), July 1, 2010 (Australasia), July 8, 2010 (New Zealand), July 16, 2010 (Europe, Xbox 360 S), June 10, 2013 (North America), June 20, 2013 (Europe, Xbox 360 E)</td>"
				+ "<td>April 20, 2016</td>"
				+ "<td>Kinect Adventures! (18 Million)</td>"
				+ "<td>84 Million</td>"
				+ "<td>$299.99 (System), $299.99 (Core System)</td>"
				+ "<td>Xbox</td>"
				+ "<td>Xbox One</td>"
				+ "<td>Seventh</td>"
				+ "<td>Xbox 360 Controller, Xbox 360 Wireless Racing Wheel, Rhythm game controllers, Big Button Pads, Xbox 360 Arcade Sticks, Ace Combat 6 Flight Stick, Kinect</td>"
				+ "<td>DVD, CD, Digital Distribution, HD DVD (discontinued)</td>"
				+ "<td>20, 60, 120, or 250 GB (Older Models) or 250 or 320 GB Detachable Hard Drives (Xbox 360 S Models), 64, 256, or 512 GB Removable Memory Cards (Original Design Only), 256 or 512 MB for Arcade Consoles (Later Models), 4 GB for Budget Level "Xbox 360 S" Consoles, 1 or 32 GB USB Storage Device (requires System Software Update), 2 GB Cloud Storage (requires Xbox LIVE Gold Membership)</td>"
				+ "<td>Xbox 360 System Software</td>"
				+ "<td>3.2 GHz PowerPC Tri-Core Xenon</td>"
				+ "<td>500 MHz ATI Xenos</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">11</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>PlayStation 4 (PS4)</td>"
				+ "<td>Sony Interactive Entertainment</td>"
				+ "<td>Sony, Foxconn</td>"
				+ "<td>Home Video Game Console</td>"
				+ "<td>November 15, 2013 (North America), November 29, 2013 (PAL), February 22, 2014 (Japan)</td>"
				+ "<td>TBD</td>"
				+ "<td>Uncharted 4: A Thief's End (8.7 Million)</td>"
				+ "<td>73.6 Million</td>"
				+ "<td>$399.99</td>"
				+ "<td>PlayStation 3</td>"
				+ "<td>TBD</td>"
				+ "<td>Eighth</td>"
				+ "<td>DualShock 4, PlayStation Move, PlayStation Vita</td>"
				+ "<td>Blu-Ray Disc, DVD</td>"
				+ "<td>500 GB, or 1 TB Hard Drive</td>"
				+ "<td>PlayStation 4 System Software</td>"
				+ "<td>Semi-Custom 8-Core AMD x86-64 Jaguar 1.6 GHz CPU (Integrated Into APU), Secondary Low Power Processor (For Background Tasks)</td>"
				+ "<td>Semi-Custom AMD GCN Radeon</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">12</a>, <a href=" + "Website About Me - Works Cited - mobile.html" + ">13</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>GameCube</td>"
				+ "<td>Nintendo</td>"
				+ "<td>Nintendo, Foxconn</td>"
				+ "<td>Home Video Game Console</td>"
				+ "<td>September 14, 2001 (Japan), November 18, 2001 (North America), May 3, 2002 (Europe), May 17, 2002 (Australasia)</td>"
				+ "<td>February 22, 2007</td>" 
				+ "<td>Super Smash Bros. Melee (7.09 Million)</td>"
				+ "<td>21.74 Million</td>"
				+ "<td>$199</td>"
				+ "<td>Nintendo 64</td>"
				+ "<td>Wii</td>"
				+ "<td>Sixth</td>"
				+ "<td>GameCube Controller, WaveBird, Game Boy Advance, various other input devices</td>"
				+ "<td>Nintendo GameCube Game Disc, Game Pak (Game Boy Player required)</td>"
				+ "<td>None, 16 GB Nintendo GameCube Memory Card</td>"
				+ "<td>Dolphin OS</td>"
				+ "<td>IBM PowerPC Gekko @ 486 MHz</td>"
				+ "<td>ATI Flipper @ 162 MHz</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">14</a>, <a href=" + "Website About Me - Works Cited - mobile.html" + ">6</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Wii</td>"
				+ "<td>Nintendo</td>"
				+ "<td>Foxconn</td>"
				+ "<td>Home Video Game Console</td>"
				+ "<td>November 19, 2006 (North America), December 2, 2006 (Japan), December 7, 2006 (Australasia), December 8, 2006 (Europe, Original), October 23, 2011 (North America), November 4, 2011 (Europe), November 11, 2011 (Australasia), Family Edition), December 7, 2012 (Canada), March 22, 2013 (Europe), November 17, 2013 (North America, Mini)</td>"
				+ "<td>October 20, 2013 (Japan, Overall) October 1, 2011 (North America), November 1, 2011 (Europe and Australasia, Original Model), October 20, 2013 (Europe), January 1, 2017 (North America, Family Edition), January 1, 2017 (Mini, Worldwide)</td>"
				+ "<td>Wii Sports (82.78 Million), Mario Kart Wii (36.75 Million)</td>"
				+ "<td>101.63 Million</td>"
				+ "<td>$249</td>"
				+ "<td>GameCube</td>"
				+ "<td>Wii U</td>"
				+ "<td>Seventh</td>"
				+ "<td>Wii Remote (Plus), Wii Balance Board, Nintendo GameCube Controller, Nintendo DS</td>"
				+ "<td>Wii Optical Disc, GameCube Game Disc, Digital Distribution (Wii Shop Channel)</td>"
				+ "<td>512 MB Internal Flash Memory, SD/SDHC card, GameCube Memory Card</td>"
				+ "<td>Wii System Software</td>"
				+ "<td>729 MHz IBM PowerPC " + "Broadway" + "</td>"
				+ "<td>243 MHz ATI " + "Hollywood" + "</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">15</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Nintendo 64</td>"
				+ "<td>Nintendo Integrated Research & Development (IRD)</td>"
				+ "<td>Nintendo</td>"
				+ "<td>Home Video Game Console</td>"
				+ "<td>June 23, 1996 (Japan), September 26, 1996 (North America, Limited) September 29, 1996 (North America (Official) and Brazil), March 1, 1997 (Europe and Australasia)</td>"
				+ "<td>April 30, 2002 (Japan), May 16 2003 (Europe, Australasia and Brazil), November 30, 2003 (North America)</td>"
				+ "<td>Super Mario 64 (11.62 Million)</td>"
				+ "<td>32.93 Million</td>"
				+ "<td>$199</td>"
				+ "<td>Super Nintendo Entertainment System (SNES)</td>"
				+ "<td>GameCube</td>"
				+ "<td>Fifth</td>"
				+ "<td>Nintendo 64 Controller</td>"
				+ "<td>Nintendo 64 Game Pak, Magnetic Disc (64DD)</td>"
				+ "<td>64 MB Game Pak, 256 Kbit (32 KB) Controller Pak</td>"
				+ "<td>None</td>"
				+ "<td>64-Bit NEC VR4300 @ 93.75 MHz</td>"
				+ "<td>SGI RCP @ 62.5 MHz</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">16</a>, <a href=" + "Website About Me - Works Cited - mobile.html" + ">6</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Super Nintendo Entertainment System (SNES)</td>"
				+ "<td>Nintendo</td>"
				+ "<td>Nintendo</td>"
				+ "<td>Home Video Game Console</td>"
				+ "<td>November 21, 1990 (Japan), November 25, 1990 (South Korea), August 23, 1991 (North America), April 11, 1992 (United Kingdom and Ireland), June 1, 1992 (Europe), July 3, 1992 (Australasia), September 1, 1992 (Brazil)</td>"
				+ "<td>September 11, 1999 (North America), April 1, 2003 (South Korea), September 25, 2003 (Japan), December 31, 2003 (Brazil)</td>"
				+ "<td>Super Mario World (20.60 Million), Donkey Kong Country (9 Million), Super Mario Kart (8 Million), Street Fighter II: The World Warrior (6.3 Million)</td>"
				+ "<td>49.10 Million</td>"
				+ "<td>$199</td>"
				+ "<td>Nintendo Entertainment System (NES)</td>"
				+ "<td>Nintendo 64</td>"
				+ "<td>Fourth</td>"
				+ "<td>SNES Controller</td>"
				+ "<td>ROM Cartridge</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>Ricoh 5A22 @ 3.58 MHz</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">17</a>, <a href=" + "Website About Me - Works Cited - mobile.html" + ">6</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Game Boy Advance (GBA)</td>"
				+ "<td>Nintendo</td>"
				+ "<td>Nintendo</td>"
				+ "<td>Handheld Game Console</td>"
				+ "<td>March 21, 2001 (Japan), June 11, 2001 (North America), June 22, 2001 (PAL), June 8, 2004 (China)</td>"
				+ "<td>May 15, 2010 (Worldwide)</td>"
				+ "<td>Pok&eacute;mon Ruby and Sapphire (16 Million)</td>"
				+ "<td>81.51 Million</td>"
				+ "<td>$99.99</td>"
				+ "<td>Game Boy Color (GBC)</td>"
				+ "<td>Nintendo DS</td>"
				+ "<td>Sixth</td>"
				+ "<td>None</td>"
				+ "<td>ROM cartridge</td>"
				+ "<td>32 KB Internal, 256 KB External, 96 KB VRAM</td>"
				+ "<td>None</td>"
				+ "<td>ARM7tdMI @ 16.78 MHz, Zilog Z80 @ 8 or 4 MHz</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">18</a>, <a href=" + "Website About Me - Works Cited - mobile.html" + ">6</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>PlayStation (PS)</td>"
				+ "<td>Sony Computer Entertainment</td>"
				+ "<td>Sony</td>"
				+ "<td>Home Video Game Console</td>"
				+ "<td>December 4, 1994 (Japan), September 9, 1995 (North America), September 29, 1995 (Europe), November 15, 1995 (Australasia, Original), July 7, 2000 (Japan), September 19, 2000 (North America), September 29, 2000 (Europe, PS One)</td>"
				+ "<td>March 23, 2006 (Worldwide)</td>"
				+ "<td>Gran Turismo (10.85 Million)</td>"
				+ "<td>102.49 Million</td>"
				+ "<td>$299</td>"
				+ "<td>None</td>"
				+ "<td>PlayStation 2</td>"
				+ "<td>Fifth</td>"
				+ "<td>PlayStation Controller, Dual Analog Controller, DualShock</td>"
				+ "<td>CD-ROM</td>"
				+ "<td>Memory Card</td>"
				+ "<td>None</td>"
				+ "<td>R3000 @ 33.8688 MHz</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">19</a>, <a href=" + "Website About Me - Works Cited - mobile.html" + ">6</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>PlayStation 2 (PS2)</td>"
				+ "<td>Sony Computer Entertainment</td>"
				+ "<td>Sony</td>"
				+ "<td>Home Video Game Console</td>"
				+ "<td>March 4, 2000 (Japan), October 26, 2000 (North America), November 24, 2000 (Europe), November 30, 2000 (Australasia, Original), October 29, 2004 (Europe), November 3, 2004 (Japan), November 25, 2004 (North America), December 2, 2004 (Australasia, Slimline)</td>"
				+ "<td>December 28, 2012 (Japan), January 4, 2013 (Worldwide)</td>"
				+ "<td>Grand Theft Auto: San Andreas (17.33 Million)</td>"
				+ "<td>155 Million</td>"
				+ "<td>$299</td>"
				+ "<td>PlayStation</td>"
				+ "<td>PlayStation 3</td>"
				+ "<td>Sixth</td>"
				+ "<td>DualShock 2, DualShock, EyeToy</td>"
				+ "<td>DVD, CD</td>"
				+ "<td>40 GB Hard Drive, 8 MB PlayStation 2 Memory Card, 128 KB PlayStation Memory Card</td>"
				+ "<td>None</td>"
				+ "<td>" + "Emotion Engine" + "@ 300 MHz</td>"
				+ "<td>150 MHz " + "Graphics Synthesizer" + "</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">20</a>, <a href=" + "Website About Me - Works Cited - mobile.html" + ">6</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Sega Genesis</td>"
				+ "<td>Sega</td>"
				+ "<td>Sega</td>"
				+ "<td>Home Video Game Console</td>"
				+ "<td>October 29, 1988 (Japan), August 14, 1989 (North America), August 14, 1990 (South Korea), September 1, 1990 (PAL and Brazil)</td>"
				+ "<td>January 1, 1997 (Worldwide, Sega), January 1, 1999 (North America, Majesco Entertainment)</td>"
				+ "<td>Sonic the Hedgehog (15 Million)</td>"
				+ "<td>30.75 Million</td>"
				+ "<td>$189</td>"
				+ "<td>Master System</td>"
				+ "<td>Sega Saturn</td>"
				+ "<td>Fourth</td>"
				+ "<td>Sega Genesis Controller</td>"
				+ "<td>ROM cartridge</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>Motorola 68000 @ 7.6 MHz, Zilog Z80 @ 3.58 MHz</td>"
				+ "<td>None</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">21</a>, <a href=" + "Website About Me - Works Cited - mobile.html" + ">6</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Super NES Classic Edition</td>"
				+ "<td>Nintendo</td>"
				+ "<td>Nintendo</td>"
				+ "<td>Dedicated Console</td>"
				+ "<td>September 29, 2017 (North America and Europe), September 30, 2017 (Australia), October 5, 2017 (Japan)</td>"
				+ "<td>TBD</td>"
				+ "<td>None</td>"
				+ "<td>4 Million</td>"
				+ "<td>$79.99</td>"
				+ "<td>NES Classic Edition</td>"
				+ "<td>TBD</td>"
				+ "<td>None</td>"
				+ "<td>Super NES Classic Edition Controller, Classic Controller</td>"
				+ "<td>Internal Flash Memory</td>"
				+ "<td>512 MB NAND Flash Memory</td>"
				+ "<td>Linux</td>"
				+ "<td>4 x ARM Cortex-A7</td>"
				+ "<td>Mali-400 MP</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">22</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Game Gear</td>"
				+ "<td>Sega</td>"
				+ "<td>Sega</td>"
				+ "<td>Handheld Game Console</td>"
				+ "<td>October 6, 1990 (Japan), April 1, 1991 (North America and Europe), January 1, 1992 (Europe)</td>"
				+ "<td>April 30, 1997 (Sega), April 30, 2001 (Majesco Entertainment)</td>"
				+ "<td>Land of Illusion Starring Mickey Mouse (20 Million)</td>"
				+ "<td>10.62 Million</td>"
				+ "<td>$149.99</td>"
				+ "<td>None</td>"
				+ "<td>Genesis Nomad</td>"
				+ "<td>Fourth</td>"
				+ "<td>None</td>"
				+ "<td>None</td>"
				+ "<td>8kB RAM, 16RkB VRAM</td>"
				+ "<td>None</td>"
				+ "<td>Zilog Z80 @ 3.5 MHz</td>"
				+ "<td>160 x 144 Pixel Resolution, 4096-Color Palette, 32 Colors On-Screen</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">23</a>, <a href=" + "Website About Me - Works Cited - mobile.html" + ">24</a></td>"
			+ "</tr>"
		+ "</table>";
	// obtain a reference to the <div>
	myDiv = document.getElementById("myDivFavoriteGamingConsolesElement");
	// add content to the <div> elementFromPoint
	myDiv.innerHTML = string;
}
