function OperatingSystemsProcess()
{
	// Create HTML code
	var string;
	string = "<table border = " + "3" + ">"
			+ "<caption>Operation Systems</caption>"
			+ "<tr>"
				+ "<th>Name</th>"
				+ "<th>Developer(s)</th>"
				+ "<th>Date of Release</th>"
				+ "<th>Date of Availability</th>"
				+ "<th>Source Model(s)</th>"
				+ "<th>Kernel type</th>"
				+ "<th>Update Method(s)</th>"
				+ "<th>Platform(s)</th>"
				+ "<th>Resource Number</th>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Microsoft Windows 7</td>"
				+ "<td>Microsoft</td>"
				+ "<td>July 22, 2009</td>"
				+ "<td>October 22, 2009</td>"
				+ "<td>Closed Source and Shared Source</td>"
				+ "<td>Hybrid</td>"
				+ "<td>Windows Update</td>"
				+ "<td>IA-32 and x86-64</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">1</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Microsoft Windows 8</td>"
				+ "<td>Microsoft</td>"
				+ "<td>August 1, 2012</td>"
				+ "<td>October 26, 2012</td>"
				+ "<td>Closed Source and Shared Source</td>"
				+ "<td>Hybrid</td>"
				+ "<td>Windows Update, Windows Store, Windows Server Update Services</td>"
				+ "<td>IA-32 and x64</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">2</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Microsoft Windows 8.1</td>"
				+ "<td>Microsoft</td>"
				+ "<td>August 27, 2013</td>"
				+ "<td>October 17, 2013</td>"
				+ "<td>None</td>"
				+ "<td>Hybrid</td>"
				+ "<td>Windows Update, Windows Store, Windows Server Update Services</td>"
				+ "<td>IA-32 and x64</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">3</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Microsoft Windows 10</td>"
				+ "<td>Microsoft</td>"
				+ "<td>July 15, 2015</td>"
				+ "<td>July 29, 2015</td>"
				+ "<td>Closed Source and Shared Source (Windows Driver Frameworks is now open-source)</td>"
				+ "<td>Hybrid (Windows NT)</td>"
				+ "<td>Windows Update, Windows Store, Windows Server Update Services</td>"
				+ "<td>IA-32, x86-64, and ARM64 (as of version 1709)</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">4</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Android</td>"
				+ "<td>Google., Open Handset, Open Handset Alliance</td>"
				+ "<td>September 23, 2008</td>"
				+ "<td>September 23, 2008</td>"
				+ "<td>Open Source and In Most Devices With Proprietary Components</td>"
				+ "<td>Monlithic (modified Linux kernel)</td>"
				+ "<td>None</td>"
				+ "<td>32-bit and 64-bit ARM, x86, x86-64, MIPS and MIPS64</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">5</a></td>"
			+ "</tr>"
			+ "<tr>"
				+ "<td>Windows XP</td>"
				+ "<td>Microsoft</td>"
				+ "<td>August 24, 2001</td>"
				+ "<td>October 25, 2001</td>"
				+ "<td>Closed Source, Shared Source</td>"
				+ "<td>Hybrid</td>"
				+ "<td>Windows Update, Windows Server Update Services (WSUS), System Center Configuration Manager (SCCM)</td>"
				+ "<td>IA-32, x86-64 and Itanium</td>"
				+ "<td><a href=" + "Website About Me - Works Cited - mobile.html" + ">6</a></td>"
			+ "</tr>"
		+ "</table>";
	// obtain a reference to the <div>
	myDiv = document.getElementById("myDivOperatingSystemsElement");
	// add content to the <div> elementFromPoint
	myDiv.innerHTML = string;
}
